### PR TITLE
Adding frontend & backend project scaffolding

### PR DESCRIPTION
**Pull request by bethanyann**
Add the backend Java Spring Boot initial setup and frontend React project built with vite.

### CODE REVIEW

**Comment by bethanyann** [comment]
This can be merged once all of the codeowners have been added to the project

**Comment by bethanyann** [comment]
> Could we add a gitignore for backend to exclude /target so we're not pushing binary files. Or is this something that I should open an issue to resolve?

You can open an issue or ask Ryan to make one and add it after this PR gets merged. Good call!

**Review by coffee2theorems — CHANGES_REQUESTED** [review]
LGTM!

**Review by coffee2theorems — APPROVED** [review]
lgtm

**Pull request merged**
