### PR TITLE
adding missing imports to fix vite build

### PR DESCRIPTION
**Pull request by bethanyann**
### Description of the changes included in this pull request

When I pulled latest from main, there was a build error when running `npm run dev` resulting from a missing `axios` import and a missing `material ui` import 

### Screenshots

image

### Setup or Testing Instructions

 pull changes in this branch, run `npm import`  and attempt to build the project, hopefully no errors occur from import issues.

### CODE REVIEW

**Comment by bethanyann** [comment]
@coffee2theorems  this should fix it.

**Review by coffee2theorems — APPROVED** [review]
Looks good.

**Review by em-ess — APPROVED** [review]
Exactly the issue I just ran into haha my bad for not looking at PRs!!! LGTM!!

**Comment by bethanyann** [comment]
@em-ess Should be all fixed now, thank you!

**Pull request merged**
