### PR TITLE
Connected landing page to log in page.

### PR DESCRIPTION
**Pull request by seishinleblanc**
### Description of the changes included in this pull request

Connected the sign in button on the landing page.

### CODE REVIEW

**Review by bduran04 — COMMENTED** [review]
hey Seishin, this is great, but i was hoping to use something like the useNavigate method so it could help with creating state so that we can switch between a log in and log out button - im open to your thoughts though :) 
example

**Comment by seishinleblanc** [comment]
That makes sense! I wasn't sure exactly where we were going with the nav bar functionality so I just quickly wired up what we had to make it easier to navigate. I can go ahead and fix this to give us at least log in and out functionality.

**Comment by bethanyann** [comment]
Hey @seishinleblanc, nice work with this! 
I don't see an issue on the board for this work at all, though, so can you make an issue for this in the GitHub project board, assign yourself to it, and put it in the "Code Reviews" column to track your work?

**Review by bethanyann — CHANGES_REQUESTED** [review]
blocking merge until a ticket is created that goes along with this work, and is put into the correct column in the project board.

**Comment by seishinleblanc** [comment]
Although this was originally about connecting the landing page, since it connects via the nav bar I'm thinking that this mostly likely just belongs with the nav bar task.

**Pull request closed without merging**
