### PR TITLE
Recipe card component

### PR DESCRIPTION
**Pull request by sohostory**
### Description of the changes included in this pull request
Made the recipe card to hold basic information to display on the dashboard.
Recipe container holds all of the card and will display on the dashboard.

The Botton for "+" isn't functional just yet. need to add API call to backend once that's set.

### Screenshots
image

### Setup or Testing Instructions
No need for additional install. Using Stack to align few items.

### CODE REVIEW

**Comment by em-ess** [comment]
Looks amazing!!! :D Awesome job!

**Review by em-ess — DISMISSED** [review]

**Comment by bduran04** [comment]
Can we please remove the calories, please? that way we can keep the "at a glance" info in one line

**Comment by sohostory** [comment]
> Can we remove the calories, please? that way we can keep the "at a glance" info in one line

absolutely! I'll make that change now

**Review by coffee2theorems — APPROVED** [review]

**Comment by seishinleblanc** [comment]
I agree with keeping the "at a glance" to one line, but perhaps the calories should stay in place of something else? Just a thought but I feel that might be the primary nutrient factor for most people.

**Review by seishinleblanc — APPROVED** [review]

**Pull request merged**
