### PR TITLE
Added name to CODEOWNERS.

### PR DESCRIPTION
**Pull request by seishinleblanc**

### CODE REVIEW

**Review by LSeward0421 — DISMISSED** [review]
✅

**Comment by wcouturiaux** [comment]
@seishinleblanc looks like there are some merge conflicts to resolve to get your changes merged, if you have any questions regarding them feel free to reach out.

**Review by wcouturiaux — DISMISSED** [review]
👍

**Review by wcouturiaux — DISMISSED** [review]
💯

**Review by wcouturiaux — APPROVED** [review]
👍

**Pull request merged**
