### PR TITLE
feature/myGroceryListAPI

### PR DESCRIPTION
**Pull request by em-ess**
### Description of the changes included in this pull request
Attempt at connecting with backend

### CODE REVIEW

**Review by bduran04 — DISMISSED** [review]
looks good!

**Review by Dissurender — DISMISSED** [review]
need to verify that changing the food -> name
Merging for now

**Review by wcouturiaux — APPROVED** [review]
For try out with Rhyn

**Review by wcouturiaux — APPROVED** [review]

**Review by Dissurender — APPROVED** [review]
merge fix

**Comment by Dissurender** [comment]
No issues with the field name change

**Pull request merged**
