### PR TITLE
Feature/createMyRecipesPage

### PR DESCRIPTION
**Pull request by em-ess**
### Description of the changes included in this pull request
Created new route and component page for "/myrecipes"

Needs to be added to navbar once that component is out and it also needs to authenticate if user logged in

EXTRA!!! Added my dashboard as a menu item to the sidebar with correct path - thought this would be useful if user wanted to go back to their dashboard

### CODE REVIEW

**Comment by em-ess** [comment]
Waiting on NavBar component - filled with the same info on login page.

**Comment by seishinleblanc** [comment]
Just to confirm, are you talking about the nav bar as in the side bar and not the upper nav bar?

**Comment by em-ess** [comment]
You right, I meant the sidebar

**Review by coffee2theorems — APPROVED** [review]
image
 LGTM

**Review by Dissurender — APPROVED** [review]
Pulled down and verified that the /myrecipes page exists :100:

**Review by Dissurender — APPROVED** [review]
Re-approval! :+1:

**Review by coffee2theorems — APPROVED** [review]
all good!

**Comment by em-ess** [comment]
@coffee2theorems @Dissurender yall are my saviors 🙏🏼🙏🏼

**Pull request merged**
