### PR TITLE
Belle landingpage

### PR DESCRIPTION
**Pull request by bduran04**

### CODE REVIEW

**Comment by bduran04** [comment]
created the first draft for the landing page; text is still WIP 
Screen_Shot_2024-04-08_at_1 16 26_AM

**Review by KINYUI1 — APPROVED** [review]
this looks amazing

**Review by wcouturiaux — DISMISSED** [review]
🎸  Amazing work!!

**Review by wcouturiaux — APPROVED** [review]
Reviewing again, I think the timing with the merge of the previous messed it up.

**Review by bduran04 — COMMENTED** [review]
Test Comment

**Review by bethanyann — APPROVED** [review]

**Pull request merged**
