### PR TITLE
add name in codeowners.txt file

### PR DESCRIPTION
**Pull request by bduran04**

### CODE REVIEW

**Review by wcouturiaux — APPROVED** [review]
🍾

**Review by wcouturiaux — COMMENTED** [review]
Looks like due to timing, there are some merge conflicts to resolve.

**Review by Dissurender — APPROVED** [review]
Should be good to go now!

**Comment by Dissurender** [comment]
Just make sure to take care of the merge 👍

**Comment by bduran04** [comment]
name added on another branch; this matter is considered resolved.

**Pull request closed without merging**
