### PR TITLE
Corrected  CODEOWNERS.txt

### PR DESCRIPTION
**Pull request by humayoonrafei**

### CODE REVIEW

**Review by em-ess — CHANGES_REQUESTED** [review]
I think you need to add to line 10 and use * not #!

**Review by em-ess — DISMISSED** [review]

**Review by wcouturiaux — APPROVED** [review]
Nice work!!

**Comment by humayoonrafei** [comment]
Thank you!

**Review by wcouturiaux — CHANGES_REQUESTED** [review]
It looks like everything is removed and adding back coffee2theorems.

**Pull request closed without merging**
