### PR TITLE
Belle menu dashboard wip

### PR DESCRIPTION
**Pull request by bduran04**
###created dashboard page, routing for dashboard page is WIP since we want to ensure that only authenticated users may access this page, menu bar started but having trouble with positioning
Screen Shot 2024-04-11 at 9 31 04 AM

### CODE REVIEW

**Review by Dissurender — APPROVED** [review]
Good progress! Keep it up :100:

**Review by em-ess — APPROVED** [review]
LGTM

**Review by bethanyann — APPROVED** [review]
Nice work!

**Review by Dissurender — APPROVED** [review]
:cake:

**Pull request merged**
