### PR TITLE
Feature/dashboard search bar

### PR DESCRIPTION
**Pull request by em-ess**
### Description of the changes included in this pull request

Creating search bar component - created dummy list of recipes with ingredients

### CODE REVIEW

**Review by bduran04 — DISMISSED** [review]
Approved - noice :)

**Review by sohostory — DISMISSED** [review]
Looks good so far. I can't fully test without implementation.

**Review by coffee2theorems — APPROVED** [review]
LGTM

**Review by Dissurender — APPROVED** [review]
Wrapping up the review for merge

**Pull request merged**
